## 70. CHILD
### Definition
The term required is about kinship, not age. I.e. give the most generic term for an individual offspring of human parents, not 'non-adult'. Give the term for an individual child, not a collective term like 'offspring', 'issue'. If the most basic term in your language is, like English 'child', a cover term for both senses of 'child', i.e. offspring and non-adult, then obviously this general term is the appropriate one to select. So select French enfant, German Kind. If your language has no such cover term, but necessarily different basic words, then select the kinship, offspring term, not a term specifically for non-adult. So for Spanish, for example, seelct hijo rather than niño. Avoid terms specific to either male or female children, i.e. 'son', 'daughter'. If there is no cover-term, prefer the more general or default term, e.g. the term used when the sex of the child is unknown, or in the plural. If no term can be considered more basic or default, select the term for a male child. In Spanish, for example, select 'hijo'. In languages where terms differ by the sex of the parent considered, prefer a generic term wherever possible, e.g. the term used when referring to both parents together, i.e. their child. If no term can be considered more basic or default, select the term used for the mother's perspective. Avoid terms specifically for children of certain ages, e.g. baby, infant, youth. Avoid animal terms, where different. (CoBL)

### Contexts
1. My sister has only one child. 2. I have three children. 3. She doesn’t have children yet.

