## 70. РЕБЁНОК
### Определение
Термин родства, а не возраста, т.е. самое общее слово для потомства людей, а не значение ‘не взрослый’.Слово для отдельного ребёнка, не собирательные слова вроде ‘потомство’. Если в языке оба значения выражаются одним словом, надо его вводить. Если нет — вводится именно слово со значением ‘отпрыск’ (например, исп. hijo вм. niño). Не использовать слова, маркированные по полу (‘сын’, ‘дочь’). Если таких слов нет, ввести слово, используемое в случае, когда пол неизвестен или во множественном числе. Если и в этом случае мужской и женский вариант равнозначны, использовать мужской.Если слово зависит от пола родителя, использовать самое нейтральное слово, например, такое, которое употребляется при упоминании обоих родителей вместе. Если такого слова нет, использовать слово для ребёнка по матери. Не использовать слова для отдельных возрастных групп (<i>младенец</i>, <i>юноша</i>). Не использовать термины для животных, если отличаются. (CoBL) 

### Контексты
1. У моей сестры только один ребёнок. 2. У меня трое детей. 3. У неё ещё нет детей. 

