---
title: "Concepts"
---

```{r, include=FALSE}
source("shared.R")
```

```{r,include=FALSE,eval=TRUE}
# Generate concept pages

sapply(seq_along(concepts$no),function(i){
    preamble <- paste0("---","\n",
                       "title: \"", concepts$no[i], ". ", concepts$rus[i], " / ", concepts$eng[i], "\"\n",
                       "params: ", "\n",
                       " concept.id: \"", concepts$no[i], "\"\n",
                       " def.ru: \"", concepts$def_RU[i], "\"\n",
                       " def.en: \"", concepts$def_EN[i], "\"\n",
                       " cx.ru: \"", concepts$cx_RU[i], "\"\n",
                       " cx.en: \"", concepts$cx_EN[i], "\"\n",
                       "---", "\n")
    body <- readLines("_concept-template.Rmd")
    text <- c(preamble, body)
    writeLines(text,paste0("_concepts/", concepts$no[i],".Rmd"))
  })
```

```{r render table 1}

# Place links to concept definitions
mutate(concepts,rus = paste0("<a href = '",
                       no,
                        ".html' target='_blank'>",
                        rus,
                        "</a>"),
          eng = paste0("<a href = '",
                        no,
                        ".html' target='_blank'>",
                        eng,
                        "</a>")) ->
concepts

# Filter out only main counterparts for comparative concepts
filter(forms, aux == "" & excl == "" & lc.id != 0) -> display

# Add Russian and English columns and remove unnecessary columns
mutate(display, rus = "",
                eng = "",
                subentry = NULL,
                aux = NULL,
                excl = NULL,
                gender = as.factor(gender),
                lang = as.factor(lang)) -> display

# Populate Russian and English columns with corresponding names and URLs
# for(i in 1:nrow(display)) {
#  display$rus[i] <- concepts$rus[concepts$no == display$lc.id[i]]
#  display$eng[i] <- concepts$eng[concepts$no == display$lc.id[i]]
#}

# Create a named list for language names
langnames <- as.list(langs$lang.name)
names(langnames) <- as.list(langs$lang.id)

# Collapse lexeme variants into single rows, spread the table
  display %>% group_by(lc.id,lang) %>% mutate(orthographic = paste(orthographic, collapse="; "), phonemic = paste(phonemic, collapse="; "), ipa = paste(ipa, collapse="; ")) %>% slice(1) %>% ungroup() %>% group_by(lex.id,lang) %>% mutate(orthographic = paste(orthographic, collapse=", "), phonemic = paste(phonemic, collapse=", "), ipa = paste(ipa, collapse=", ")) %>% slice(1) %>% ungroup() %>% transmute(sort = sapply(lc.id, function(x) {concepts %>% filter(no == x) %>% pull(sort) %>% ifelse(x != 0 && . != 0, ., 9999)}), id = lc.id, rus = sapply(lc.id, function(x) {ifelse(x != 0, concepts %>% filter(no == x) %>% pull(rus), "")}), eng = sapply(lc.id, function(x) {ifelse(x != 0, concepts %>% filter(no == x) %>% pull(eng), "")}), orthographic = orthographic, phonemic = phonemic, ipa = ipa, lang = lang) %>% gather("type","text",ipa,phonemic,orthographic) %>% unite(lang.type, c(lang,type), sep = ".")  %>% spread(lang.type,text) -> display.spread

# # Replace the concept numbers with corresponding names and URLs
# for(i in 1:nrow(display.spread)) {
#  #display$rus[i] <- concepts$rus[concepts$no == display$rus[i]]
#  concepts %>% filter(no == display.spread$id[i]) %>% pull(rus) -> display.spread$rus[i]
#  concepts %>% filter(no == display.spread$id[i]) %>% pull(eng) -> display.spread$eng[i]  
#  concepts %>% filter(no == display.spread$id[i]) %>% pull(sort) -> display.spread$sort[i]
#  #display$eng[i] <- concepts$eng[concepts$no == display$eng[i]]
# }

grep(".*\\.ipa$",colnames(display.spread))-1 -> cols.ipa
grep(".*\\.phonemic$",colnames(display.spread))-1 -> cols.phonemic
grep(".*\\.orthographic$",colnames(display.spread))-1 -> cols.orthographic

# Generate human-readable column names
sapply(as.list(names(display.spread)), function(n){
  case_when(
    n == "sort" ~ "",
    n == "id" ~ "LexCauc ID",
    n == "rus" ~ "Concept (Russian)",
    n == "eng" ~ "Concept (English)",
    grepl("\\.ipa|\\.phonemic|\\.orthographic", n) ~ as.character(langnames[strsplit(n, "\\.")[[1]][1]]),
    # grepl(".ipa", n) ~ paste0(langnames[strsplit(n, "\\.")[[1]][1]]," (IPA)"),
    # grepl(".phonemic", n) ~ paste0(langnames[strsplit(n, "\\.")[[1]][1]]," (phonemic)"),
    # grepl(".orthographic", n) ~ paste0(langnames[strsplit(n, "\\.")[[1]][1]]," (orthographic)"),
    TRUE ~ n
  )
}) -> newcols

# Display the table
datatable(display.spread, escape = FALSE, rownames = FALSE,
          extensions = c('ColReorder', 'Buttons', 'FixedHeader'),
          filter = 'top',
          colnames = newcols,
          options = list(
            columnDefs = list(list(targets = cols.ipa, visible = FALSE),
                              list(targets = cols.orthographic, visible = TRUE),
                              list(targets = cols.phonemic, visible = FALSE),
                              list(targets = c(0), visible = FALSE)
            ),
            order = list(list(0,"asc")),
            dom = 'Btip', 
            autoWidth = TRUE, 
            colReorder = TRUE, 
            buttons = list(
              list(
                extend = 'collection',
                text = 'Transcription',
                buttons = list(
                  list(
                    extend = 'colvisGroup',
                    text = "orthographic",
                    show = cols.orthographic,
                    hide = append(cols.phonemic,cols.ipa)
                  ),
                  list(
                    extend = 'colvisGroup',
                    text = "phonemic",
                    show = cols.phonemic,
                    hide = append(cols.ipa,cols.orthographic)
                  ),                
                  list(
                    extend = 'colvisGroup',
                    text = "IPA",
                    show = cols.ipa,
                    hide = append(cols.phonemic,cols.orthographic)
                  )                    
                )
              )
            ),
            fixedHeader = list(headerOffset = 45),
            pageLength = 50))
```